### ISSUE TITLE
archive-get subcommand should unpack tarball

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-db-utils#16]
The existing --extract option should also unpack the downloaded file.  The --output option should be interpreted as a folder and the file downloaded to there (filename derived from URL).  If --extract is provided, the file (which will be the decompressed tarball) should be unpacked to that folder and removed.  This end result should be equivalent to piping curl into zstd into tar.

**Comment by georgepisaltu** [comment]
Closed in https://github.com/casper-network/casper-db-utils/pull/17
