### ISSUE TITLE
Clean up `casper-db-utils`

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-db-utils#19]
Remove accumulated technical debt in `casper-db-utils`, specifically:
- revisit all file writes where overwrites can happen and allow them only through `--overwrite` parameter
- explore replacing the current logging implementation with `env-logger`
- ensure long-running commands give user feedback in some way (logfile or `stdout`)

**Comment by georgepisaltu** [comment]
Also relevant to this ticket, parse the code for inconsistent usage of the same parameters. The most glaring example is `DB_PATH`, which is sometimes the path to a `storage.lmdb` file, sometimes a path to the directory containing `storage.lmdb` and `data.lmdb` files. We should be consistent with what the API looks like across commands.

**Comment by georgepisaltu** [comment]
Closed in #20
