### ISSUE TITLE
Feature request: Show progress as percentage + ETA?

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/casper-db-utils#22]
I'm experimenting with the ```compact-trie``` subcommand and I see lots of that messages:
```
2022-08-30T19:46:12.065183935Z [INFO] trie migration progress: bytes copied 3713498179, tries copied 6709106
```

Is it possible to add percentage please? Ideally also some rough ETA.

**Comment by georgepisaltu** [comment]
Hey, thanks for taking the time to open the issue. Unfortunately for that specific command there is no realistic way to tell how many tries you have left to copy without traversing the tree, so the only way to provide some rough ETA would be to traverse the graph beforehand, which is going to take a long time anyway and is counterproductive IMO.

The other commands which have some sort of known amount of work to be done have progress tracking implemented as a percentage. It's just not the case for `compact-trie`. Hope this answers your question. I'll close this for now, feel free to reopen if you have anything to add.
