### ISSUE TITLE
Update dependencies to stable state

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-db-utils#37]
Follow up on https://github.com/casper-network/casper-node/issues/3921. The underlying problem is a dependency mismatch with casper-types and casper-node . More specifically, casper-types 1.6 (should be 3.0) had breaking changes compared to casper-types 1.5 . We should update the casper-db-utils dependencies to a stable state once the casper-types changes are sorted out.

**Comment by rafal-ch** [comment]
@RitaMAllenCA 
unassigning @georgepisaltu due to no cycles left during this sprint
