### ISSUE TITLE
release-1.4.6 trie-compact tool

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-db-utils#7]
We need to move the code in https://github.com/casper-network/casper-node/pull/2948 to a subcommand of the db-utils tool.

The review comments should be addressed as part of this work, ideally as a separate commit to simplify the review.  Any further deviations/improvements other than changes strictly required to support the move should be kept to standalone commits too, for the same reason.

**Comment by georgepisaltu** [comment]
Closed in https://github.com/casper-network/casper-db-utils/pull/11
